# Get the Gini of a country
SELECT
    (SAMPLE(?countryLabel) AS ?key)
    ?value
{
    SELECT
        ?countryLabel
        (SAMPLE(?gini) AS ?value)
    WHERE {
        ?country wdt:P31 wd:Q6256 .
        ?country wdt:P1125 ?gini .
        ?country rdfs:label ?countryLabel . FILTER (LANG(?countryLabel)='en')
        FILTER(STR(?countryLabel) NOT IN ("Kingdom of the Netherlands", "Kingdom of Denmark"))
    }
    GROUP BY ?countryLabel
    HAVING (COUNT(?gini) = 1)
}
GROUP BY ?value
HAVING (COUNT(?countryLabel) = 1)
ORDER BY ?key
