name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Lint code
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Run tests
        run: npm run test
